### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by FelixAlvarado** [FelixAlvarado/360px#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by niartenyaw** [comment]
Nice work! See the unchecked bullet points below:

# User Auth

## Functionality

- [X] The main button with logo should link to `/`
- [X] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
    - [x] When on `/signup`, the button in the upper right says `Upload`
- [X] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [X] Errors should display for both `/signup` and `/login`.
- [X] Errors should clear when moving between `/signup` and `/login`.
- [X] Can sign up a user
- [X] Can sign in as a user
- [X] Can log out a user
- [X] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data and not the demo user
    - [x] Can't submit with enter, make sure you're using a form element!

### After Login

- [X] Should not be able to visit `/login` or `/signup`
- [X] Should be able to refresh the page and still be logged in


## Style

- [X] The site should look exactly like the actual site
- [X] All relevant elements should have `cursor: pointer` on hover
- [X] When errors are displayed, most elements should not move around the page (particularly input boxes)

**Comment by FelixAlvarado** [comment]
I just made the changes

**Comment by niartenyaw** [comment]
Awesome, looks good!
