### ISSUE TITLE
PA Review: Posting Pictures

### ISSUE THREAD

**Issue by FelixAlvarado** [FelixAlvarado/360px#3]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Adequate and appropriate seeds
- [x] Upload shows on current users profile page

**Comment by niartenyaw** [comment]
Awesome!

# Pictures

## Functionality

- [X] Can upload photo
- [x] Can view new photo in list
- [x] Can view photo in show page/modal
- [x] Can edit photo attributes

## Styling

- [X] Looks like the actual site

**Comment by FelixAlvarado** [comment]
Finished!

**Comment by niartenyaw** [comment]
Nice! One more small thing and then you can close:

- [x] Would like to be able to push `<esc>` to quit out of the show modal

**Comment by FelixAlvarado** [comment]
fixed it

**Comment by niartenyaw** [comment]
Nice work! you can close
