### ISSUE TITLE
PA Review: Follows

### ISSUE THREAD

**Issue by FelixAlvarado** [FelixAlvarado/360px#4]
- [x] Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
 - [x] Presentational Components and Containers
- [x]  Styling
 - [x] Adequate and appropriate seeds
- [x] Pressing follow button updates both button and follower/followings in database

**Comment by niartenyaw** [comment]
Looks great! Feel free to close.

I did have a little bit of hover-effect trouble where it wouldn't always show the effect. Something you can look at later if you have time.
